version: '3'
services:
  php:
    build: /home/gustavo/Documentos/GitHub/Lista 2/Lista-2/Desafio 2
    container_name: meu-php
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - /home/gustavo/Documentos/GitHub/Lista 2/Lista-2/Desafio 2:/var/www/html
    links:
      - db

  db:
    image: postgres:latest
    container_name: meu-postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=root
