services:
  php:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8100:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    links:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: exemplo
    ports:
      - "8101:5432"

#docker compose up -d /// docker compose stop /// docker compose down
# criar no postgre dois banco de dados, um chamado gerenciador e outro chamado trivia. 
#depois de fazer a conexão no dbeaver clicar com o botao direito lá no "Bancos de dados" e novo banco, botar os respectivos nomes e usar template 0 ou 1 no "bancos de dados modelos"
# quando entrar no navegador botar localhost/gerenciador_tarefas ou localhost/trivia.
